#!/usr/bin/env bash
# Import every workflows/**/*.json into n8n via its CLI (inside the container).
# Idempotent: re-imports overwrite by id.
# After import, resolves named subworkflow IDs and writes them to .env.runtime,
# which compose loads on next `make up`.
set -euo pipefail

shopt -s globstar nullglob
files=(workflows/**/*.json)
if (( ${#files[@]} == 0 )); then
  echo "no workflows to import."
  exit 0
fi

for f in "${files[@]}"; do
  echo ">> importing $f"
  # Add UUID id if missing (n8n requires it)
  python3 -c "import json,uuid,sys;wf=json.load(open(sys.argv[1]));wf.setdefault('id',str(uuid.uuid4()));json.dump(wf,open('/tmp/wf_temp.json','w'),indent=2)" "$f"
  docker compose cp /tmp/wf_temp.json n8n:/tmp/wf.json
  docker compose exec -T n8n n8n import:workflow --input=/tmp/wf.json
done

docker compose exec -T n8n n8n update:workflow --all --active=true || true

echo ">> resolving subworkflow IDs"
declare -A NAME_TO_VAR=(
  ["Terry · SSH Exec (sub-workflow)"]="WF_SSH_EXEC"
  ["Terry · Approval Gate (Telegram)"]="WF_APPROVAL"
  ["Terry · Incident Commander"]="WF_COMMANDER"
)
echo "# auto-generated by import-workflows.sh — DO NOT EDIT" > .env.runtime
for name in "${!NAME_TO_VAR[@]}"; do
  var="${NAME_TO_VAR[$name]}"
  id=$(docker compose exec -T postgres psql -U "${POSTGRES_USER:-terry}" -d "${POSTGRES_DB:-terry}" -tA \
       -c "SELECT id FROM workflow_entity WHERE name = \$\$$name\$\$ LIMIT 1" 2>/dev/null | tr -d '[:space:]' || echo "")
  if [ -n "$id" ]; then
    echo "$var=$id" >> .env.runtime
    echo "   $var = $id"
  else
    echo "   $var = (not found — check workflow name)"
  fi
done

echo "import complete. Re-run 'make up' so n8n picks up .env.runtime."
